### ISSUE TITLE
v3.0.0 not working.

### ISSUE THREAD

**Issue by arzyu** [EasyPi/docker-shadowsocks-libev#3]
I was using this `docker-compose.yml` below. It's broken after I deployed it on Ubuntu 16.04.

```
version: '2'
services:
  shadowsocks:
    image: easypi/shadowsocks-libev
    ports:
      - '8388:8388'
    environment:
      - PASSWORD=**********
    restart: always
```

Getting back to the version 2.6.3 works for me.
