### ISSUE TITLE
Can't change the server side port.

### ISSUE THREAD

**Issue by lotc** [EasyPi/docker-shadowsocks-libev#9]
I try to follow the default guide to get [docker-compose.yml](https://github.com/EasyPi/docker-shadowsocks-libev/raw/master/docker-compose.yml), then run `docker-compose up -d server` .
But the default server listen port is `8388`.

I've tried to modify the `ports` part on `docker-compose.yml`. However, the `easypi/shadowsocks-libev` image defines the `EXPOSE` port in `8388`.
Is it possible to change the port via `docker-compose.yml`? Or I have to build it without using `docker-compose.yml` ?

**Comment by vimagick** [comment]
You can change port bindings on host:

```yaml
server:
  image: easypi/shadowsocks-libev
  ports:
    - "18388:8388/tcp"
    - "18388:8388/udp"
  environment:
    - METHOD=aes-256-cfb
    - PASSWORD=5ouMnqPyzseL
  restart: always
```

Clients need to connect to port 18388 from now on.
